[env]
platform = ststm32
board = nucleo_f767zi
framework = stm32cube
monitor_speed = 115200
lib_ldf_mode = deep+

build_src_filter = +<*> -<tinyml_app_*.cc>

build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14
build_flags =
    -O2
    -std=gnu++17
    -D TF_LITE_STATIC_MEMORY
    -D NDEBUG
    -D CMSIS_NN
    -I lib/tflm
    -I lib/tflm/third_party/flatbuffers/include
    -I lib/tflm/third_party/gemmlowp
    -I lib/tflm/third_party/ruy
    -I lib/tflm/third_party/kissfft
    -I lib/tflm/third_party/kissfft/tools
    -I lib/tflm/third_party/cmsis_nn
    -I lib/tflm/third_party/cmsis_nn/Include
    -fno-exceptions
    -fno-rtti

platform_packages =
    toolchain-gccarmnoneeabi @ ~1.120301.0

[env:cnn]
build_src_filter = ${env.build_src_filter} +<tinyml_app_cnn.cc>

[env:mlp]
build_src_filter = ${env.build_src_filter} +<tinyml_app_mlp.cc>

[env:rf]
build_src_filter = ${env.build_src_filter} +<tinyml_app_rf.cc>

[env:svm]
build_src_filter = ${env.build_src_filter} +<tinyml_app_svm.cc>