[env]
platform = ststm32
board = nucleo_f767zi
framework = stm32cube
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB

[env:cnn]
board_build.cmake_extra_args = -DTINYML_MODEL=cnn
board_build.embed_files = cnn_classifier.tflite

[env:mlp]
board_build.cmake_extra_args = -DTINYML_MODEL=mlp
board_build.embed_files = mlp_classifier.tflite

[env:rf]
board_build.cmake_extra_args = -DTINYML_MODEL=rf

[env:svm]
board_build.cmake_extra_args = -DTINYML_MODEL=svm