[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB

[env:cnn]
board_build.cmake_extra_args = -DTINYML_MODEL=cnn

[env:mlp]
board_build.cmake_extra_args = -DTINYML_MODEL=mlp

[env:rf]
board_build.cmake_extra_args = -DTINYML_MODEL=rf

[env:svm]
board_build.cmake_extra_args = -DTINYML_MODEL=svm