[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = 
    -Os
board_build.embed_files =
  cnn_classifier.tflite
  mlp_classifier.tflite