"""Test beats compiled into the energy firmware (<model>_energy builds).

During the current/energy test the board has no serial link to the host
(it is powered only through the INA226, see power_logger/README.md), so it
can't receive beats like in the DS2 test (benchmark_serial.py). Instead a
fixed set of DS2 beats is compiled into the firmware as
include/models/energy_beats.h, and the board runs its inferences on them.

The beats are raw (unfiltered), like the ones benchmark_serial.py sends: the
firmware filters them once at boot (filter_sos) and times/measures only the
inference, the same part the DS2 test reports as inference_us. Every
scored class (N, S, V, F) is represented, so models whose cost depends on
the input (e.g. the depth reached in the Random Forest trees) are measured
on a mix of paths, not only on normal beats.

Run by pipeline.py (step 2), or directly:
    python ml/src/energy_beats.py
"""

import sys
from pathlib import Path

import numpy as np

from load_data import (SCORED_CLASSES, TEST_RECORDS, cache_is_current, classes,
                       dataset_cache_path, select_records)

# Same dataset configuration as benchmark_serial.py.
FEATURE = 'MLII'
INPUT_SIZE = 256
BEATS_PER_CLASS = 8
SEED = 1
HEADER_NAME = 'energy_beats.h'

repository_directory = Path(__file__).resolve().parents[2]
firmware_directories = (repository_directory / 'esp32_firmware',
                        repository_directory / 'stm32_firmware')


def select_energy_beats():
    """(beats, rr, labels) of up to BEATS_PER_CLASS DS2 beats of each scored
    class, interleaved (N, S, V, F, N, S, ...) so consecutive inferences
    change class. None if the dataset cache is missing or outdated."""
    cache_file = dataset_cache_path(FEATURE, INPUT_SIZE)
    if not cache_file.exists():
        print(f'[WARNING] Dataset cache not found: {cache_file}. '
              'Run the training (pipeline step 1) first.')
        return None
    with np.load(cache_file) as data:
        if not cache_is_current(data):
            print('[WARNING] Dataset cache is from an older version. '
                  'Run the training (pipeline step 1) again.')
            return None
        mask = select_records(data['records'], TEST_RECORDS)
        X, rr, y = data['X'][mask], data['rr'][mask], data['y'][mask].astype(int)

    rng = np.random.default_rng(SEED)
    per_class = []
    for name in SCORED_CLASSES:
        indices = np.flatnonzero(y == classes.index(name))
        count = min(BEATS_PER_CLASS, len(indices))
        per_class.append(list(rng.choice(indices, size=count, replace=False)))

    order = []
    for position in range(BEATS_PER_CLASS):
        order += [indices[position] for indices in per_class if position < len(indices)]
    order = np.array(order)
    return X[order], rr[order], y[order]


def c_float(value):
    """C float literal: '%.9g' round-trips a float32, and a '.0' is added to
    whole numbers ('2f' is not valid C/C++, '2.0f' is)."""
    text = f'{float(value):.9g}'
    if not any(character in text for character in '.en'):
        text += '.0'
    return text + 'f'


def c_array(values):
    return ', '.join(c_float(value) for value in values)


def write_header(destination, beats, rr, labels):
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open('w', encoding='ascii', newline='\n') as file:
        file.write(
            '// Generated by ml/src/energy_beats.py from the DS2 test set. Do not edit.\n'
            '// Raw (unfiltered) beats + RR features for the energy firmware\n'
            '// (energy_app.cc), which has no serial link during the test.\n'
            '#pragma once\n\n'
            '#include "tinyml_common.h"\n\n'
            f'constexpr int kEnergyBeatCount = {len(beats)};\n\n'
            'static const float kEnergyBeats[kEnergyBeatCount][kInputSamples] = {\n')
        for beat in beats:
            file.write(f'    {{{c_array(beat)}}},\n')
        file.write('};\n\n'
                   'static const float kEnergyRr[kEnergyBeatCount][kRrFeatures] = {\n')
        for values in rr:
            file.write(f'    {{{c_array(values)}}},\n')
        file.write('};\n\n'
                   '// True class of each beat (not used by the firmware, for reference).\n'
                   'static const int kEnergyLabels[kEnergyBeatCount] = {'
                   + ', '.join(str(int(label)) for label in labels) + '};\n')


def write_energy_beats(firmware_directory):
    """Writes include/models/energy_beats.h into one firmware project.
    Returns False (with a warning) if the dataset cache isn't available."""
    selected = select_energy_beats()
    if selected is None:
        return False
    beats, rr, labels = selected
    destination = Path(firmware_directory) / 'include' / 'models' / HEADER_NAME
    write_header(destination, beats, rr, labels)
    counts = ', '.join(f'{classes[c]} {int(np.sum(labels == c))}' for c in np.unique(labels))
    print(f'  -> Wrote {HEADER_NAME} ({len(beats)} DS2 beats: {counts}) '
          f'to {Path(firmware_directory).name} models folder.')
    return True


if __name__ == '__main__':
    ok = all([write_energy_beats(directory) for directory in firmware_directories])
    sys.exit(0 if ok else 1)
